apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: banking-service
  name: banking-service
  namespace: banka-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-service
  template:
    metadata:
      labels:
        app: banking-service
    spec:
      containers:
        - image: harbor.k8s.elab.rs/banka-1/banking-service:latest
          imagePullPolicy: Always
          name: banking-service
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          env:
            - name: THC_PORT
              value: "8082"
            - name: THC_PATH
              value: "/actuator/health"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://banka-1-primary.banka-1.svc:5432/banking-service-db?useUnicode=true&characterEncoding=UTF-8
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: user
                  name: banka-1-pguser-banking-service-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: banka-1-pguser-banking-service-user
            - name: SPRING_ACTIVEMQ_BROKER_URL
              value: tcp://banka-1-message-broker:61616?jms.prefetchPolicy.all=1&jms.redeliveryPolicy.maximumRedeliveries=0
            - name: FRONTEND_URL
              value: https://banka-1.si.raf.edu.rs
            - name: SPRING_SQL_INIT_MODE
              value: always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: banking-service
  name: banking-service
  namespace: banka-1
spec:
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: banking-service
  type: ClusterIP
