apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name}}-frontend
  name: {{ .Release.Name}}-frontend
  namespace: {{ .Release.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name}}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name}}-frontend
    spec:
      containers:
        - image: harbor.k8s.elab.rs/banka-1/frontend-k8s:{{.Values.imageTag}}
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 80
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 2
          name: frontend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name}}-frontend
  name: {{ .Release.Name}}-frontend
  namespace: {{ .Release.Namespace}}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: {{ .Release.Name}}-frontend
  type: ClusterIP
