apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name}}-idp
  name: {{ .Release.Name}}-idp
  namespace: {{ .Release.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name}}-idp
  template:
    metadata:
      labels:
        app: {{ .Release.Name}}-idp
    spec:
      containers:
        - image: "harbor.k8s.elab.rs/banka-1/idp:{{ .Values.imageTag}}"
          imagePullPolicy: Always
          name: user-service
{{/*          livenessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /actuator/health*/}}
{{/*              port: 9000*/}}
{{/*            initialDelaySeconds: 60*/}}
{{/*            periodSeconds: 10*/}}
{{/*            failureThreshold: 3*/}}
{{/*          readinessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /actuator/health*/}}
{{/*              port: 9000*/}}
{{/*            initialDelaySeconds: 30*/}}
{{/*            periodSeconds: 10*/}}
{{/*            failureThreshold: 10*/}}
          env:
            # Healthchecks
{{/*            - name: THC_PORT*/}}
{{/*              value: "9000"*/}}
{{/*            - name: THC_PATH*/}}
{{/*              value: "/actuator/health"*/}}
            # Database
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ .Release.Name}}-primary.{{ .Release.Namespace}}.svc:5432/user-service-db?useUnicode=true&characterEncoding=UTF-8
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: user
                  name: {{ .Release.Name}}-pguser-user-service-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Release.Name}}-pguser-user-service-user
            - name: SPRING_SQL_INIT_MODE
              value: always
            # Redis
            - name: SPRING_DATA_REDIS_HOST
              value: {{ .Release.Name}}-redis-master.{{ .Release.Namespace}}.svc
            - name: SPRING_DATA_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-password
                  name: banka-1-redis
            - name: SPRING_SECURITY_OAUTH2_AUTHORIZATIONSERVER_ISSUER
              value: https://{{ .Values.idpDomain}}
            - name: SERVER_FORWARD_HEADERS_STRATEGY
              value: native
            # Maybe force HTTPS redirects, I really am not sure...
            - name: SERVER_HTTP2_ENABLED
              value: "true"
            - name: SERVER_TOMCAT_REMOTE_IP_HEADER
              value: "X-Forwarded-For"
            - name: SERVER_TOMCAT_PROTOCOL_HEADER
              value: "X-Forwarded-Proto"


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name}}-idp
  name: {{ .Release.Name}}-idp
  namespace: {{ .Release.Namespace}}
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: {{ .Release.Name}}-idp
  type: ClusterIP
