apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name}}-notification-service
  name: {{ .Release.Name}}-notification-service
  namespace: {{ .Release.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name}}-notification-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name}}-notification-service
    spec:
      containers:
        - image: harbor.k8s.elab.rs/banka-1/notification-service:{{ .Values.imageTag}}
          imagePullPolicy: Always
          name: notification-service
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          env:
            - name: THC_PORT
              value: "8080"
            - name: THC_PATH
              value: "/actuator/health"
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ .Release.Name}}-primary.{{ .Release.Namespace}}.svc:5432/notification-service-db?useUnicode=true&characterEncoding=UTF-8
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: user
                  name: {{ .Release.Name}}-pguser-notification-service-user
            - name: SPRING_H2_CONSOLE_ENABLED
              value: "false"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Release.Name}}-pguser-notification-service-user
            - name: SPRING_ACTIVEMQ_BROKER_URL
              value: tcp://{{ .Release.Name}}-message-broker:61616?jms.prefetchPolicy.all=1&jms.redeliveryPolicy.maximumRedeliveries=0
            - name: FRONTEND_URL
              value: https://{{ .Values.appDomain }}
            - name: SPRING_SQL_INIT_MODE
              value: always
            - name: SPRING_OUTPUT_ANSI_ENABLED
              value: always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name}}-notification-service
  name: {{ .Release.Name}}-notification-service
  namespace: {{ .Release.Namespace}}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ .Release.Name}}-notification-service
  type: ClusterIP
