apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name}}-support-service
  name: {{ .Release.Name}}-support-service
  namespace: {{ .Release.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name}}-support-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name}}-support-service
    spec:
      containers:
        - image: harbor.k8s.elab.rs/banka-1/support-service:{{ .Values.imageTag}}
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              port: 8000
              path: /health
          readinessProbe:
            httpGet:
              port: 8000
              path: /health
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 5
          name: support-service
          env:
            - name: GOOGLE_API
              valueFrom:
                secretKeyRef:
                  key: api-key
                  name: google-api
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name}}-support-service
  name: {{ .Release.Name}}-support-service
  namespace: {{ .Release.Namespace}}
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: {{ .Release.Name}}-support-service
  type: ClusterIP
